#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/


############# Configuration #############
#bspc monitor -d   '⋍' '⋎' '⋏' '⋐' '⋑' '⋓' '⋔' '⋕' '⋊' '⋿'
bspc monitor -d 1 2 3 4 5 6 7 8 9 0


############# Multi-monitor Setup #############
#bspc monitor DVI-I-1 -d I II III IV
#bspc monitor HDMI-0 -d V VI VII VIII

############# Set Compose Key to R-Alt #############
setxkbmap -option compose:ralt &

############# Common BSPWM Configuration  #############
bspc config border_width        	2
bspc config window_gap         		10
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config focus_follows_pointer 	true
bspc config top_padding 			30

############# Color Settings #############
#bspc config focused_border_color 	"#367BF0" 
#bspc config normal_border_color 	"#1A1A1A"

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

##################
## window rules ##
##################

############# Workspace 1 (system Tools) #############
bspc rule -a GParted desktop='^1' state=floating follow=on
bspc rule -a htop desktop='^1' follow=on focus=on
bspc rule -a fslint-gui desktop='^1' follow=on focus=on
bspc rule -a Lxappearance desktop='^1' state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings desktop='^1' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^1' state=floating follow=on
bspc rule -a Pavucontrol desktop='^1' state=floating follow=on
bspc rule -a Exo-helper-1 desktop='^1' state=floating follow=on
bspc rule -a Lxrandr desktop='^1' state=floating follow=on
bspc rule -a Arandr desktop='^1' state=floating follow=on
bspc rule -a luckybackup desktop='^1' state=floating follow=on
bspc rule -a grsync desktop='^1' state=floating follow=on

#############  Workspace 2 (Web Browser Tools) #############
bspc rule -a Firefox desktop='^2' follow=on focus=on

############# Workspace 3 (Web File Tools) #############
bspc rule -a Filezilla desktop='^3' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^3' follow=on focus=on
bspc rule -a Filezilla desktop='^3' follow=on focus=on

############# Workspace 4 (text-processing) #############
bspc rule -a libreoffice-startcenter desktop='^4' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a Mousepad desktop='^4' follow=on focus=on
bspc rule -a libreoffice-base desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-draw desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a zim.py desktop='^4' follow=on focus=on

############# Workspace 5 (graphics-utilities) #############
bspc rule -a Viewnior desktop='^5' follow=on focus=on
bspc rule -a Gcolor2 desktop='^5' follow=on focus=on
bspc rule -a Gimp desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
bspc rule -a Oomox desktop='^5' follow=on focus=on

############# Workspace 6 (videocasting) #############
bspc rule -a kazam desktop='^6' follow=on focus=on
bspc rule -a obs desktop='^6' follow=on focus=on
bspc rule -a simplescreenrecorder desktop='^6' follow=on focus=on
#bspc rule -a Xfburn desktop='^6' follow=on focus=on

############# Workspace 7 (music- voice) #############
bspc rule -a Audacity desktop='^7' follow=on focus=on
bspc rule -a deepin-voice-recorder desktop='^7' follow=on focus=on
bspc rule -a moc desktop='^7' follow=on focus=on

############# Workspace 8 (programming tools) #############
bspc rule -a Geany desktop='^8' follow=on focus=on
bspc rule -a gvim desktop='^8' follow=on focus=on

############# Workspace 9 (email & communications) #############
bspc rule -a Thunderbird desktop='^9' follow=on 
bspc rule -a Skype desktop='^9' state=floating follow=on focus=on

############# Workspace 10 (Presentations etc.) #############
bspc rule -a Evince desktop='^10' state=floating follow=on
bspc rule -a Calibre desktop='^10' state=floating follow=on
bspc rule -a djview4 desktop='^10' state=floating follow=on

############# pseudo tiled rules #############
bspc rule -a Thunar           pseudo_tiled=on focus=on
bspc rule -a Skype            pseudo_tiled=on focus=on
bspc rule -a File-roller      pseudo_tiled=on focus=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Catfish 		  pseudo_tiled=on

############# need to be floating #############
bspc rule -a Gnome-mpv state=floating follow=on
bspc rule -a Synaptic state=floating follow=on focus=on
bspc rule -a rofi state=floating follow=on focus=on
bspc rule -a smtube state=floating follow=on
bspc rule -a desktop-session-exit state=floating follow=on
bspc rule -a gnome-disks state=floating

############# don't manage my conky & systemtray :/ #############
#bspc rule -a Conky state=floating manage=off
#bspc rule -a stalonetray state=floating manage=off

###############
## autostart ##
###############

############# Load bitmap fonts #############
xset fp+ ~/.fonts/misc &

############# Compositor Selections #############
############# xcompmgr (disable other compositors to use this one) #############
#pkill xcompmgr
#xcompmgr -fF -I-.004 -O-.004 -D2 -cC -t-4 -l-6 -r6 &

############# xfwm4 (disable other compositors to use this one) #############
#pkill xfwm4
#xfwm4 &

############# Compton (disable other compositors to use this one) #############
pkill compton
compton -b &

############# system tray #############
#pkill stalonetray
#stalonetray &

############# network applet #############
nm-applet &

############# clipboard manager #############
#pkill clipit
#clipit &

############# volume icon #############
pkill volumeicon
volumeicon &

############# keybind daemon #############
pkill sxhkd
sxhkd &

############# start term to load polybar colors from pywal #############
pkill roxterm
	roxterm &
	
############# music is my friend :( #############
pkill mocp
	roxterm -e mocp &

############# reload the xsettingsd, a minimal x settings daemon #############
pkill xsettingsd
xsettingsd &

############# set the wallpaper #############
#pkill feh
#feh --randomize --bg-fill ~/.local/share/wallpapers/*

############# load dunst #############
pkill dunst
dunst &

############# reload the cursor theme #############
xsetroot -cursor_name left_ptr

############# Panel Setups #############

############# tint2 panel #############
pkill tint2
tint2 &

############# bspwm panel #############
#pkill panel-bspwm
#	panel-bspwm &

############# or polybar? #############
pkill polybar
~/.config/polybar/launch.sh &

############# Dropbox #############
pkill dropbox
	dropbox start &
	
############# Mega #############
#pkill megasync
#	megasync &
	
############# Light locker on suspend #############
pkill light-locker
light-locker --lock-on-suspend &

############# Use PyWal to set system to match desktop wallpaper colors ############# 
pkill wal
~/.config/wal/pywal.sh &
#wal -iterative -i "$HOME/.local/share/wallpapers" &
